openapi: "3.0.3"
info:
  title: "AmazingProduct API"
  description: "AmazingProduct API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /products:
    get:
      summary: "GET products"
      operationId: "readAll"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
    post:
      summary: "POST products"
      operationId: "createOne"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: "Bad Request - All fields must be filled"
  /products/{id}:
    get:
      summary: "GET products/{id}"
      operationId: "readOne"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: "Bad Request - Invalid ID provided"
        "404":
          description: "Not Found - Product not found"
    put:
      summary: "PUT products/{id}"
      operationId: "updateOne"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: "Bad Request - Valid ID must be provided and All fields must be filled"
        "404":
          description: "Not Found - Product not found"
    delete:
      summary: "DELETE products/{id}"
      operationId: "deleteOne"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Not Found - Product not found"
components:
  schemas:
    Product:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        category:
          type: "string"
        price:
          type: "number"
          format: "double"