### Read All
GET http://localhost:8080/products

### Read One
GET http://localhost:8080/products/1

### Read One with negative id
GET http://localhost:8080/products/-1

### Add One
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "pomme",
  "category": "fruits",
  "price": 1
}

### Add One with empty name
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "",
  "category": "fruits",
  "price": 1
}

### Add One with empty category
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "pomme",
  "category": "",
  "price": 1
}

### Add One with negative price
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "pomme",
  "category": "fruits",
  "price": -1
}

### Modify One
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "banane",
  "category": "fruit",
  "price": 2
}

### Modify One with empty name
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "",
  "category": "fruit",
  "price": 2
}

### Modify One with empty category
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "banane",
  "category": "",
  "price": 2
}

### Modify One with negative price
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "banane",
  "category": "fruit",
  "price": -1
}

### Delete One
DELETE http://localhost:8080/products/1

### Delete One with negative id
DELETE http://localhost:8080/products/-1